### ISSUE TITLE
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:

### ISSUE THREAD

**Issue by xenoterracide** [hexojs/hexo-migrator-rss#10]
seeing if I can import my blogger into hexo, and how it looks,  here's what I'm running and it's public so ... ```hexo migrate rss https://feeds.feedburner.com/xenoterracide```

```
INFO  Post found: pkgcore the victor
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2010-06-02 23:36:45
        ^
    at generateError (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1045:9)
    at composeNode (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at Object.load (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\hexo\post.js:122:18
    at tryCatcher (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
FATAL can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2010-06-02 23:36:45
        ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 2, column 5:
    date: 2010-06-02 23:36:45
        ^
    at generateError (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:162:10)
    at throwError (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:168:9)
    at readBlockMapping (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1045:9)
    at composeNode (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1331:12)
    at readDocument (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1493:3)
    at loadDocuments (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1549:5)
    at Object.load (C:\Users\xeno\IdeaProjects\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1566:19)
    at C:\Users\xeno\IdeaProjects\blog\node_modules\hexo\lib\hexo\post.js:122:18
    at tryCatcher (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xeno\IdeaProjects\blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by Bharath2511** [comment]
I think you need to give a space between 'date' and ':'

**Comment by dacuotecuo** [comment]
Did it solved yet？could anyone give any advice？

**Comment by curbengh** [comment]
Seem related to "double quote in title" https://github.com/hexojs/hexo-migrator-wordpress/issues/17.
Fixed in https://github.com/hexojs/hexo-migrator-rss/pull/64.

**Comment by limxtop1989** [comment]
> title: English-introduction
> date: 2021-08-18 21:23:28
Add a space after colon solve my issue.
