### ISSUE TITLE
"not a feed" when: hexo migrate rss http://liguanghe.github.io 

### ISSUE THREAD

**Issue by liguanghe** [hexojs/hexo-migrator-rss#11]
## my ENV version
Mac 10.12
hexo: 3.3.6
hexo-cli: 1.0.2
os: Darwin 16.5.0 darwin x64
http_parser: 2.7.0
node: 6.10.1
v8: 5.1.281.95
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k

## I do this: hexo migrate rss http://liguanghe.github.io

got this:
INFO  Analyzing http://liguanghe.github.io...
INFO  0 posts migrated.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: Not a feed
    at FeedParser.handleEnd (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/main.js:129:13)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at Object.SAXStream._parser.onend (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:184:8)
    at emit (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:615:33)
    at end (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:654:3)
    at Object.end (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:149:24)
    at SAXStream.end (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:234:16)
    at FeedParser._flush (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/main.js:1010:15)
    at FeedParser.<anonymous> (_stream_transform.js:118:12)
    at FeedParser.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at FeedParser.emit (events.js:185:7)
    at prefinish (_stream_writable.js:505:12)
    at finishMaybe (_stream_writable.js:513:7)
    at endWritable (_stream_writable.js:525:3)
    at FeedParser.Writable.end (_stream_writable.js:490:5)
    at Request.onend (internal/streams/legacy.js:44:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/liguanghe/liguanghe.github.io/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
FATAL Not a feed
Error: Not a feed
    at FeedParser.handleEnd (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/main.js:129:13)
    at emitNone (events.js:86:13)
    at SAXStream.emit (events.js:185:7)
    at Object.SAXStream._parser.onend (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:184:8)
    at emit (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:615:33)
    at end (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:654:3)
    at Object.end (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:149:24)
    at SAXStream.end (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/node_modules/sax/lib/sax.js:234:16)
    at FeedParser._flush (/Users/liguanghe/liguanghe.github.io/node_modules/feedparser/main.js:1010:15)
    at FeedParser.<anonymous> (_stream_transform.js:118:12)
    at FeedParser.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at FeedParser.emit (events.js:185:7)
    at prefinish (_stream_writable.js:505:12)
    at finishMaybe (_stream_writable.js:513:7)
    at endWritable (_stream_writable.js:525:3)
    at FeedParser.Writable.end (_stream_writable.js:490:5)
    at Request.onend (internal/streams/legacy.js:44:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/liguanghe/liguanghe.github.io/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)

What shall I do? Thanks.

**Comment by NoahDragon** [comment]
The source url should be an RSS feed, it usually is `atom.xml`. 

I saw your website already up and running using Hexo. Does the issue still exist?

**Comment by liguanghe** [comment]
thanks for your attention. @NoahDragon 
yes, it still there. 
In the past, i built Hexo - Github pages - blog. Using the plugin to have one rss. This time i rebuilt the blog, maybe this is why?  If so, what i can do?

last time has rss2.xml, not atom.xml

I tried it just now, it still like this:

INFO  Analyzing http://liguanghe.github.io...
INFO  0 posts migrated.
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html

**Comment by NoahDragon** [comment]
I couldn't find the rss feed on your website.
To generate a rss feed, you will need the plugin https://github.com/hexojs/hexo-generator-feed .

**Comment by liguanghe** [comment]
@NoahDragon  that works, thanks a lot . 
Problem: not a feed.
Solvtion Way: plugin https://github.com/hexojs/hexo-generator-feed .
